INSERT INTO tb_roles (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_roles (authority) VALUES ('ROLE_MEDICO');
INSERT INTO tb_roles (authority) VALUES ('ROLE_PACIENTE');

INSERT INTO TB_USUARIOS (EMAIL,PASSWORD,PRIMEIRO_NOME,SOBRE_NOME) VALUES ('edson@gmail.com','$2a$10$PZZILrO22dxfvxXpSw/lHOGrfZuHU8qGn0Nb0IoSrYvUl6i1MgmI6','Edson','Campolina');
INSERT INTO TB_USUARIOS (EMAIL,PASSWORD,PRIMEIRO_NOME,SOBRE_NOME) VALUES ('teste@gmail.com','$2a$10$PZZILrO22dxfvxXpSw/lHOGrfZuHU8qGn0Nb0IoSrYvUl6i1MgmI6','Teste','Sobrenome');
INSERT INTO TB_USUARIOS (EMAIL,PASSWORD,PRIMEIRO_NOME,SOBRE_NOME) VALUES ('anna@gmail.com','$2a$10$PZZILrO22dxfvxXpSw/lHOGrfZuHU8qGn0Nb0IoSrYvUl6i1MgmI6','Anna','Laura');
INSERT INTO TB_USUARIOS (EMAIL,PASSWORD,PRIMEIRO_NOME,SOBRE_NOME) VALUES ('rodolfo@gmail.com','$2a$10$PZZILrO22dxfvxXpSw/lHOGrfZuHU8qGn0Nb0IoSrYvUl6i1MgmI6','Rodolfo','Rocha');
INSERT INTO TB_USUARIOS (EMAIL,PASSWORD,PRIMEIRO_NOME,SOBRE_NOME) VALUES ('joao@gmail.com','$2a$10$PZZILrO22dxfvxXpSw/lHOGrfZuHU8qGn0Nb0IoSrYvUl6i1MgmI6','Joao','Mayrink');

INSERT INTO TB_USUARIOS_ROLES VALUES (1,1);
INSERT INTO TB_USUARIOS_ROLES VALUES (2,2);
INSERT INTO TB_USUARIOS_ROLES VALUES (3,2);
INSERT INTO TB_USUARIOS_ROLES VALUES (4,3);
INSERT INTO TB_USUARIOS_ROLES VALUES (5,3);